config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :exchange_rate
    get :list
  end

  namespace :ip do
    get :home
    get :ip_search
    get :speed_test
  end
end

app/models/concerns/constants/currency.rb
module Constants
  module Currency
    DEFAULT_TO   = 'GBP'
    DEFAULT_FROM = 'USD'

    DEFAULT_FROM_AND_TO = {from: DEFAULT_FROM, to: DEFAULT_TO}

    POPULAR_CURRENCIES = %w(USD INR EUR GBP JPY)
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  layout 'currencies/application'

  def home
    # convert_currencies = currency_service.get_currencies_from_ip('27.170.56.62')
    convert_currencies = currency_service.get_currencies_from_ip(request.ip)
    redirect_to action: :convert, from: convert_currencies[:from], to: convert_currencies[:to]
  end

  def convert
    @currencies         = _currencies
    @exchange_rate      = present(_exchange_rate, ::Presenters::Currency::ExchangeRatePresenter)
    @history_response   = present(_history_response, ::Presenters::Currency::HistoryResponsePresenter)
    @popular_currencies = present(_popular_currencies, ::Presenters::Currency::ExchangeRatePresenter)
  end

  def exchange_rate
    render json: currency_service.get_exchange_rate(from: params[:from], to: params[:to]).rate
  end

  def list
    @currencies = _currencies
  end

  private

  def _currencies
    present(currency_service.get_currencies, ::Presenters::Currency::CurrenciesPresenter)
  end

  def _exchange_rate
    currency_service.get_exchange_rate_with_currency_details(from: params[:from], to: params[:to])
  end

  def _history_response
    currency_service.get_currency_histories(from: params[:from], to: params[:to])
  end

  def _popular_currencies
    currency_service.get_popular_currency_exchanges(params[:from])
  end
end

app/views/currencies/_credits.html.haml
.py-3
  .alert.alert-info.text-center
    This website uses a free currency exchange service updated on top of the hour.
    Credits to:
    =link_to 'CurrencyConverterApi', 'http://currencyconverterapi.com/', target: '_blank', rel: 'noopener'

app/views/currencies/_currencies_list.html.haml
%h2.text-center Available Countries
.row
  - break_countries(countries: countries).each do |list|
    .col-md-6
      .table-responsive
        %table.table.table-striped.table-bordered{style: "width:100%"}
          %thead
            %tr
              %th= I18n.t('currency.labels.flag')
              %th= I18n.t('currency.labels.code')
              %th= I18n.t('currency.labels.currency_name')
              %th= I18n.t('currency.labels.country')
          %tbody
            - list.each do |c|
              %tr
                %td
                  %spac{class: "flag-icon flag-icon-#{c.code}"}
                %td= c.currency.code
                %td= formatted_currency_name(currency_name: c.currency.name)
                %td= c.name

app/views/currencies/_currency_details.html.haml
%h3.text-center
  Currency Details

%table.table.table-bordered
  %thead
    %tr
      %th.col-md-2.col-sm-2
      %th.col-md-5.col-sm-5 From Currency
      %th.col-md-5.col-sm-5 To Currency
  %tbody
    %tr
      %td Currency
      %td= exchange_rate.from_currency.name
      %td= exchange_rate.to_currency.name
    %tr
      %td Code
      %td= exchange_rate.from_currency.code
      %td= exchange_rate.to_currency.code
    %tr
      %td Icon
      %td
        %span{class: "currency-flag currency-flag-#{exchange_rate.from_currency.code.try(:downcase)}"}
      %td
        %span{class: "currency-flag currency-flag-#{exchange_rate.to_currency.code.try(:downcase)}"}
    %tr
      %td Symbol
      %td= exchange_rate.from_currency.symbol
      %td= exchange_rate.to_currency.symbol
    %tr
      %td Countries
      %td= exchange_rate.from_currency&.countries&.map(&:name)&.join(', ') || ''
      %td= exchange_rate.to_currency&.countries&.map(&:name)&.join(', ') || ''

app/views/currencies/_currency_header.html.haml
%h4.my-4
  #exchange-header-block
    #from-currency-name= exchange_rate.from_currency.name
    .between-text to
    #to-currency-name= exchange_rate.to_currency.name
%hr
-#= render partial: 'exchange_details', locals: {exchange_rate: exchange_rate}

app/views/currencies/_currency_input.html.haml
= form_tag currencies_convert_path, method: :get, id: 'currency-form' do
  .form-row
    .form-group.col-md-6
      = label_tag I18n.t('currency.labels.amount_from')
      .input-group.mb-3
        = text_field_tag('', 1, {placeholder: I18n.t('currency.labels.amount_from'),
                                                       id: 'from-amount',
                                                       class: 'form-control currency-input'})
        .input-group-append
          %span.input-group-text.font-weight-bold= exchange_rate.from

    .form-group.col-md-6
      = label_tag I18n.t('currency.labels.converted_to')
      .input-group.mb-3
        = text_field_tag('', exchange_rate.rate, {placeholder: I18n.t('currency.labels.converted_to'),
                                                     id: 'to-amount',
                                                     class: 'form-control currency-input'})
        .input-group-append
          %span.input-group-text.font-weight-bold= exchange_rate.to

  .form-row
    .col-md
      .form-row
        .col-md-5
          = label_tag I18n.t('currency.labels.from')
          = select_tag :from, options_from_collection_for_select(currencies, :code, :name_with_code, exchange_rate.from),
                        class: 'select2 form-control',
                        id: 'from-currency'

        .text-center.col-md-2
          = label_tag ''
          = link_to fontawesome_icon('fas fa-exchange-alt pt-4 fa-2x toggle-currency'),
            currencies_convert_path(from: exchange_rate.to, to: exchange_rate.from)

        .col-md-5
          = label_tag I18n.t('currency.labels.to')
          = select_tag :to,
                       options_from_collection_for_select(currencies, :code, :name_with_code, exchange_rate.to),
                       class: 'select2 form-control',
                       id: 'to-currency'
      %br
      .form-row
        .col-md-3
          = submit_tag(I18n.t('currency.buttons.convert'), class: 'btn btn-primary')
        .col-md-9
          Prices Updates every hour. Next update

    .col-md.text-center
      = render partial: 'exchange_details', locals: {exchange_rate: exchange_rate}

app/views/currencies/_currency_select.html.haml
%select_tag.selectpicker.form-control{'data-live-search' => 'true'}
  - @currencies.each do |c|
    %option{'data-icon': "flag-icon flag-icon-#{c.code}", 'data-subtext': " - #{c.name}"}= "#{c.currency_name.split.map(&:capitalize).join(' ')} (#{c.currency_id})"

app/views/currencies/_exchange_details.html.haml
.form-group
  = "1 #{exchange_rate.from} → #{exchange_rate.rate} #{exchange_rate.to}"
  #exchange-rate= exchange_rate.rate

app/views/currencies/_exchange_table.html.haml
%h3.text-center
  Conversion Tables
.row
  .col-md
    %table.table.table-bordered
      %thead
        %tr
          %th.text-right= exchange_rate.from
          %th= exchange_rate.to
      %tbody
        - (1000..10000).step(1000) do |number|
          %tr
            %td.text-right= exchange_rate.from_currency_base(number)
            %td.text-left= exchange_rate.from_currency_calc_amount(number)

  .col-md
    %table.table.table-bordered
      %thead
        %tr
          %th.text-right= exchange_rate.to
          %th= exchange_rate.from
      %tbody
        - (1000..10000).step(1000) do |number|
          %tr
            %td.text-right= exchange_rate.to_currency_base(number)
            %td.text-left= exchange_rate.to_currency_calc_amount(number)

app/views/currencies/_history.html.haml
.row.mb-5
  .col-md-8
    %h3.text-center
      History Graph
    %canvas#history-graph
  .col-md-4
    %h3.text-center
      History Tables
    %table.table.table-bordered
      %tbody
        %tr
          %td Highest
          %td= history_response.histories.highest
        %tr
          %td Lowest
          %td= history_response.histories.lowest
        %tr
          %td Average
          %td= history_response.histories.average
        %tr
          %td Change
          %td= history_response.histories.change_difference
        %tr
          %td % Change
          %td= history_response.histories.change_percent
        %tr
          %td Start Date
          %td= history_response.histories.start_date
        %tr
          %td End Date
          %td= history_response.histories.end_date
        %tr
          %td Total Days
          %td= history_response.histories.length

:javascript
  chart.init(JSON.parse('#{raw(history_response.chart_data)}'), 'history-graph');

app/views/currencies/_popular_currencies.html.haml
%h3.text-center
  Popular Currencies
%table.table.table-bordered
  %thead
    %tr
      %th
      -Constants::Currency::POPULAR_CURRENCIES.each do |currency|
        %th
          %span{class: "currency-flag currency-flag-#{currency.downcase}"}
          %span= currency
  %tbody
    %tr
      %td= "from #{params[:from]}"
      -Constants::Currency::POPULAR_CURRENCIES.each do |currency|
        %td
          = popular_currencies.rate_by_currency(to_code: currency, from_code: params[:from])
    %tr
      %td= "to #{params[:from]}"
      -Constants::Currency::POPULAR_CURRENCIES.each do |currency|
        %td
          = popular_currencies.rate_by_currency(to_code: params[:from], from_code: currency)

app/views/currencies/convert.html.haml
%section
  .jumbotron.search-section
    .container
      = render partial: 'currency_header', locals: {exchange_rate: @exchange_rate}

      = render partial: 'currency_input', locals: {exchange_rate: @exchange_rate, currencies: @currencies}

      = render partial: 'currencies/credits'

%section
  .container
    = render partial: 'history', locals: {history_response: @history_response}

%section
  .jumbotron{style: '#f5f8fd'}
    .container
      = render partial: 'popular_currencies', locals: {popular_currencies: @popular_currencies}

%section
  .container
    .row
      .col-md-7
        = render partial: 'exchange_table', locals: {exchange_rate: @exchange_rate}

      .col-md-5
        = render partial: 'currencies/currency_details', locals: {exchange_rate: @exchange_rate}

:javascript
  var currency = Currency.init();
  currency.bindEvents();

app/views/currencies/list.html.haml
.jumbotron.search-section.text-center
  %h3 Currencies List
.container.py-5

  - @currencies.grouped_and_sorted_by_code.each do |alphabet, currencies|
    .currency-alphabet-break
      %span= alphabet
    - currencies.each_slice(4).each do |currencies_slice|
      .row
        -currencies_slice.each do |currency|
          .col-md-3
            .currency-list.m-4.p-3
              %h5
                %span.text-left= "#{currency.code} - "
                %span.text-right{class: "currency-flag currency-flag-#{currency.code.try(:downcase)}"}
              .ellipsis.mb-2= currency.name
              -Constants::Currency::POPULAR_CURRENCIES.each do |currency_code|
                %span.mr-2
                  - next if currency_code.downcase == currency.code.try(:downcase)
                  = link_to currencies_convert_path(from: currency.code, to: currency_code) do
                    %i{class: "pr-2 currency-flag currency-flag-#{currency_code}"}