config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :exchange_rate
    get :list
  end

  namespace :ip do
    get :home
    get :ip_search
    get :speed_test
  end
end

app/controllers/ip_controller.rb
class IpController < ApplicationController
  layout 'ip/application'

  def home
    redirect_to action: :ip_search, ip_input: request.ip
  end

  def ip_search
    @ip_detail = present(_ip_details, Presenters::IpDetails::IpDetailsPresenter)
    @quality_detail = present(_ip_quality_details, Presenters::IpDetails::IpQualityPresenter)
  rescue Exceptions::IpExceptions::InvalidQueryException => e
    render 'ip/ip_error_page', status: 400, locals: { query: e.query }
  rescue Exception => e
    render template: 'ip/general_error', status: 500, locals: { error_message: e.to_s, client_ip: request.ip }
  end

  private

  def _ip_details
    ip_service.get_ip_details(params[:ip_input])
  end

  def _ip_quality_details
    ip_service.get_ip_quality_details(@ip_detail.ip)
  end
end

app/helpers/ip_helper.rb
module IpHelper

  def fraud_score_format(options = {})
    options[:value] = _fraud_score_format(options)
    quality_detail_format(options)
  end

  def quality_detail_format(options = {})
    left_border_class = options[:left_border_class].presence || 'info-left'
    content_tag :div, class: 'col-md quality-detail' do
      content_tag :div, class: "card #{left_border_class}" do
        content_tag :div, class: 'card-body ' do
          content_tag :div, class: 'row align-items-center' do
            concat _quality_text_format(options)
            concat _quality_icon_format(options)
          end
        end
      end
    end
  end

  private

  def _fraud_score_format(options = {})
    content_tag :b do
      concat _score_format(options[:value_prefix])
      concat content_tag :span, options[:value_suffix], class: options[:text_class]
    end
  end

  def _quality_icon_format(options = {})
    content_tag :div, class: 'col-auto text-right' do
      fontawesome_icon("#{options[:icon]} #{options[:text_class]}")
    end
  end

  def _quality_text_format(options = {})
    content_tag :div, class: 'col' do
      concat(content_tag :h4, options[:label])
      concat(content_tag :small, options[:value], class: options[:value_text_class])
    end
  end

  def _score_format(value)
    content_tag :b do
      concat content_tag :span, value, class: 'badge badge-pill badge-info'
      concat content_tag :span, " - "
    end
  end
end

app/views/layouts/ip/_footer.html.haml
%footer.page-footer
  .container.pb-3
    %span IP Track ©
    %span= "#{Time.now.year}"

app/views/layouts/ip/_header.html.haml
.navbar.navbar-dark.navbar-expand-lg.fixed-top.bg-white
  .container
    = link_to 'IP Details', ip_home_path, class: 'navbar-brand logo'
    %button.navbar-toggler{"data-target" => "#navbarNav", "data-toggle" => "collapse"}
      %span.sr-only Toggle navigation
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.nav.navbar-nav.ml-auto
        %li.nav-item
          = link_to 'Home', ip_home_path, class: 'nav-link active'
        %li.nav-item
          = link_to 'Speed Test', ip_speed_test_path, class: 'nav-link active'

app/views/layouts/ip/application.html.haml
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %meta{charset: 'utf-8'}
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}
    %title IP Details


    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css', integrity: 'sha256-BtbhCIbtfeVWGsqxk1vOHEYXS6qcvQvLMZqjtpWUEx8=', rel: 'stylesheet'}/

    %script{crossorigin: 'anonymous', integrity: 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=', src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'}

    %script{src: 'http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js'}
    %link{crossorigin: 'anonymous', href: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', integrity: 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO', rel: 'stylesheet'}
    %script{crossorigin: 'anonymous', integrity: 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy', src: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js', type: 'text/javascript'}

    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/currency-flags/1.8.0/currency-flags.css', integrity: 'sha256-1nLh1SuCTXvjlsdqnaw4bmW0ybmaHRzWMFuEg7iaRRM=', rel: 'stylesheet'}

    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css', integrity: 'sha256-NkXMfPcpoih3/xWDcrJcAX78pHpfwxkhNj0bAf8AMTs=', rel: 'stylesheet'}/

    %script{async: '', defer: 'defer', src: '//maps.googleapis.com/maps/api/js??sensor=false&key=AIzaSyDMFnGX9AS6gI8BpPRXPxBW6wFOQVG93L4&libraries=places', type: 'text/javascript'}

    = stylesheet_link_tag 'ip/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'ip/application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/ip/header'
    = yield
    = render partial: 'layouts/ip/footer'