config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :exchange_rate
    get :list
  end

  namespace :ip do
    get :home
    get :ip_search
    get :speed_test
  end
end

app/controllers/ride_track_controller.rb
class RideTrackController < ApplicationController

  def home
  end

  def price_estimate
    @price_estimates = ride_track_service.get_price_estimates(request: build_request)
  rescue Exceptions::RideTrack::InvalidParameters => e
    @error = e.message
  rescue Exception => e
    @error = e.message || 'Something went wrong, please try again.'
  end

  private

  def estimate_origin_params
    params.require(:origin_details).permit ESTIMATE_PARAMS_LIST
  end

  def estimate_destination_params
    params.require(:destination_details).permit ESTIMATE_PARAMS_LIST
  end

  ESTIMATE_PARAMS_LIST = [:latitude, :longitude, :city, :state, :postal_code, :country]

  def build_request
    Domains::RideTrack::PriceEstimateRequest.new(
        origin_details: estimate_origin_params,
        destination_details: estimate_destination_params
    )
  end

end

app/controllers/ride_tracks_controller.rb
class RideTracksController < ApplicationController

  layout 'ride_tracks/application'

  def home
  end

  def price_estimate
    @price_estimates = ride_track_service.get_price_estimates(request: build_request)
  rescue Exceptions::RideTrack::InvalidParameters => e
    @error = e.message
  end

  private

  def estimate_origin_params
    params.require(:origin_details).permit ESTIMATE_PARAMS_LIST
  end

  def estimate_destination_params
    params.require(:destination_details).permit ESTIMATE_PARAMS_LIST
  end

  ESTIMATE_PARAMS_LIST = [:latitude, :longitude, :city, :state, :postal_code, :country]

  def build_request
    Domains::RideTrack::PriceEstimateRequest.new(
        origin_details: estimate_origin_params,
        destination_details: estimate_destination_params
    )
  end
end

app/views/ride_track/_coordinates_search.html.erb
<%= form_tag(ride_track_price_estimate_path, method: :get, remote: true, id: 'coordinate-search') do %>
  <div class="form-group">
    <%= label_tag I18n.t('ride_track.labels.origin') %>
    <%= text_field_tag 'origin_details[address]', nil,
                       class: 'form-control',
                       id: 'origin-address',
                       placeholder: 'Central Park, Manhattan, New York, NY, USA',
                       required: true %>
  </div>
  <div class="form-group">
    <%= label_tag I18n.t('ride_track.labels.destination') %>
    <%= text_field_tag 'destination_details[address]', nil,
                       class: 'form-control',
                       id: 'destination-address',
                       placeholder: 'Times Square, Manhattan, New York, NY, USA',
                       required: true %>
  </div>

  <%= render partial: 'coordinate_details' %>

  <%= submit_tag I18n.t('ride_track.buttons.estimate'), class: 'btn btn-primary', id: 'estimate', name: 'estimate' %>
<% end %>

<script>
    $(document).ready(function () {
        coordinatesSearch.init();
    });
</script>

app/views/ride_track/_estimates.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <%= render 'ride_track/fare_details', fare_details: @price_estimates.fare_details %>
      <%= render 'ride_track/filter', filters: @price_estimates.filters %>
    </div>
  </div>

  <div class="col-md-9">
    <% @price_estimates.estimates.each_slice(4).each do |slice| %>
      <div class="ride-share-estimates pricing card-deck flex-column flex-md-row mb-3">
        <% slice.each do |pe| %>
          <%= render 'ride_track/provider_price_estimate', price_estimate: pe %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div id="directions" style='width: 100%; height: 400px;'></div>
</div>

<script>
    mapService.directions('<%= @price_estimates.request.origin.latitude %>',
        '<%= @price_estimates.request.origin.longitude %>',
        '<%= @price_estimates.request.destination.latitude %>',
        '<%= @price_estimates.request.destination.longitude %>',
        '#directions'
    );
</script>

app/views/ride_track/home_page.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="container text-center ">
      <h1><i class="fas fa-taxi"></i> Fare Estimate Online</h1>
      <h3>Instantly Calculate the Cost of a Ride!</h3>

      <hr>

      <div id="coordinates_search" class="container w-50">
        <%= render partial: 'coordinates_search' %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div id="price_estimates">
    <!--  Place Holder-->
  </div>
</div>

<%= render 'information' %>

app/views/ride_track/price_estimate.js.erb
var estimateContainer = $('#price_estimates')

<% errors = @price_estimates.try(:errors) || [@error] %>

<% if errors.try(:any?) %>
  estimateContainer.empty().html("<%=j render 'ride_track/errors', errors: errors %>");
<% elsif @price_estimates.try(:estimates).try(:any?) %>
  estimateContainer.empty().html("<%=j render 'ride_track/estimates' %>");
<% end %>