config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ride_tracks#home'

  namespace :ride_tracks do
    get :home
    get :price_estimate
  end

  namespace :currencies do
    get :home
    get :convert
    get :exchange_rate
    get :list
  end

  namespace :ip do
    get :home
    get :ip_search
    get :speed_test
  end
end

app/models/concerns/constants/currency.rb
module Constants
  module Currency
    DEFAULT_TO   = 'GBP'
    DEFAULT_FROM = 'USD'

    DEFAULT_FROM_AND_TO = {from: DEFAULT_FROM, to: DEFAULT_TO}

    POPULAR_CURRENCIES = %w(USD INR EUR GBP JPY)
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  layout 'currencies/application'

  def home
    # convert_currencies = currency_service.get_currencies_from_ip('27.170.56.62')
    convert_currencies = currency_service.get_currencies_from_ip(request.ip)
    redirect_to action: :convert, from: convert_currencies[:from], to: convert_currencies[:to]
  end

  def convert
    @currencies         = _currencies
    @exchange_rate      = present(_exchange_rate, ::Presenters::Currency::ExchangeRatePresenter)
    @history_response   = present(_history_response, ::Presenters::Currency::HistoryResponsePresenter)
    @popular_currencies = present(_popular_currencies, ::Presenters::Currency::ExchangeRatePresenter)
  end

  def exchange_rate
    render json: currency_service.get_exchange_rate(from: params[:from], to: params[:to]).rate
  end

  def list
    @currencies = _currencies
  end

  private

  def _currencies
    present(currency_service.get_currencies, ::Presenters::Currency::CurrenciesPresenter)
  end

  def _exchange_rate
    currency_service.get_exchange_rate_with_currency_details(from: params[:from], to: params[:to])
  end

  def _history_response
    currency_service.get_currency_histories(from: params[:from], to: params[:to])
  end

  def _popular_currencies
    currency_service.get_popular_currency_exchanges(params[:from])
  end
end

app/views/layouts/currencies/_footer.html.haml
%footer.py-5.bg-black
  .container
    %p.m-0.text-center.text-white.small

app/views/layouts/currencies/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.navbar-custom.fixed-top
  .container
    = link_to fontawesome_icon('fas fa-coins', 'Currency Converter'), currencies_home_path, class: 'navbar-brand'
    %button.navbar-toggler{'aria-controls': 'navbarResponsive', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', 'data-target': '#navbarResponsive', 'data-toggle': 'collapse', type: 'button'}
      %span.navbar-toggler-icon

app/views/layouts/currencies/application.html.haml
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %meta{charset: 'utf-8'}
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}
    %title Currency Convert


    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css', integrity: 'sha256-BtbhCIbtfeVWGsqxk1vOHEYXS6qcvQvLMZqjtpWUEx8=', rel: 'stylesheet'}/

    %script{crossorigin: 'anonymous', integrity: 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=', src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'}

    %script{src: 'http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js'}
    %link{crossorigin: 'anonymous', href: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css', integrity: 'sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO', rel: 'stylesheet'}
    %script{crossorigin: 'anonymous', integrity: 'sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy', src: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js'}
    %script{src: 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js', type: 'text/javascript'}

    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/css/flag-icon.min.css', integrity: 'sha256-D+ZpDJjhGxa5ffyQkuTvwii4AntFGBZa4jUhSpdlhjM=', rel: 'stylesheet'}/

    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css', integrity: 'sha256-MeSf8Rmg3b5qLFlijnpxk6l+IJkiR91//YGPCrCmogU=', rel: 'stylesheet'}/
    %script{crossorigin: 'anonymous', integrity: 'sha256-GHC3xFbrevQ0aRcWg5JElUOncXYXxTtMOuA74cWAPTw=', src: 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js'}

    %script{crossorigin: 'anonymous', integrity: 'sha256-xKeoJ50pzbUGkpQxDYHD7o7hxe0LaOGeguUidbq6vis=', src: 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js'}

    %link{crossorigin: 'anonymous', href: 'https://cdnjs.cloudflare.com/ajax/libs/currency-flags/1.8.0/currency-flags.css', integrity: 'sha256-1nLh1SuCTXvjlsdqnaw4bmW0ybmaHRzWMFuEg7iaRRM=', rel: 'stylesheet'}

    = stylesheet_link_tag    'currencies/application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'currencies/application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/currencies/header'
    = yield
    = render partial: 'layouts/currencies/footer'